- project:
    check:
      jobs: &id001
        - cabal-test:
            nodeset:
              nodes:
                - name: fedora-31
                  label: zuul-worker-f37
        - hlint:
            nodeset:
              nodes:
                - name: fedora-31
                  label: zuul-worker-f37
    gate:
      jobs: *id001
